version: '3.6'
services:
  btpns2-app:
    container_name: btpns2-app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db-mysql/3306; do sleep1; done; npm start'
    ports:
      - "3000:3000"
    restart: always
    depends_on:
    - db-mysql
  db-mysql:
    container_name: db-mysql
    build:
      context: .
      dockerfile: DockerfileMySql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: btpns
      MYSQL_USER: app_user
      MYSQL_PASSSWORD: 60132323abcd
      MYSQL_ROOT_PASSWORD: 60132323abcd
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always